/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2019-06-11 03:49:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.sell;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.model.vo.User;
import sell.model.vo.Sell;
import java.util.*;
import comment.model.vo.*;
import file.model.vo.*;

public final class sellView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1560223882666L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1560169361511L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("comment.model.vo");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("file.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("sell.model.vo.Sell");
    _jspx_imports_classes.add("user.model.vo.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"../common/error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

   //세션 객체로부터 저장된 로그인 사용자 정보 가져오기
   User userLoggedIn = (User)session.getAttribute("userLoggedIn");
   
   //쿠키 처리
   Cookie[] cookies = request.getCookies();
   boolean saveIdflag = false;
   String userId = "";
   if (cookies != null) {
      for (Cookie c : cookies) {
         
         String key = c.getName();
         String value = c.getValue();
         if ("saveId".equals(key)) {
            saveIdflag = true;
            userId = value;
         }
      }
   }
   
   

      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.4.0.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>SellBar - Flea Market For U</title>\r\n");
      out.write("\r\n");
      out.write("<!-- 부트스트랩 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\r\n");
      out.write("   integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\"\r\n");
      out.write("   crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.js\"\r\n");
      out.write("   integrity=\"sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=\"\r\n");
      out.write("   crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"\r\n");
      out.write("   integrity=\"sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49\"\r\n");
      out.write("   crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\"\r\n");
      out.write("   integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\"\r\n");
      out.write("   crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- 부트스트랩 End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("   href=\"https://fonts.googleapis.com/css?family=Gloria+Hallelujah&display=swap\"\r\n");
      out.write("   rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("   href=\"https://fonts.googleapis.com/css?family=Poor+Story&display=swap\"\r\n");
      out.write("   rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/header.css\" />\r\n");
      out.write("<link\r\n");
      out.write("   href=\"https://fonts.googleapis.com/css?family=Sunflower:300&display=swap\"\r\n");
      out.write("   rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#head-container {\r\n");
      out.write("   background-image: url(\"");
      out.print(request.getContextPath());
      out.write("/images/header.jpg\");\r\n");
      out.write("} \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("   <div id=\"head-container\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("'\">\r\n");
      out.write("   </div>\r\n");
      out.write("   <hr />\r\n");
      out.write("\r\n");
      out.write("   <aside id=\"asideLeft\">\r\n");
      out.write("      <section>\r\n");
      out.write("         ");
 if (userLoggedIn == null) { 
      out.write("\r\n");
      out.write("         <div id=\"login-container\">\r\n");
      out.write("            <br />\r\n");
      out.write("            <form action=\"");
      out.print(request.getContextPath());
      out.write("/views/user/login\" method=\"post\" id=\"loginFrm\">\r\n");
      out.write("               <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/userId.svg\" class=\"inout\">\r\n");
      out.write("               <input type=\"text\" name=\"userId\" id=\"header_userId\" value='");
      out.print(saveIdflag?userId:"" );
      out.write("' /> \r\n");
      out.write("                  <br /> \r\n");
      out.write("                  <img src=\"");
      out.print(request.getContextPath());
      out.write("/images/pwd.svg\" class=\"inout\">\r\n");
      out.write("                  <input type=\"password\" name=\"userPwd\" id=\"header_userPwd\" onkeyup=\"enterUser();\"/>\r\n");
      out.write("                   <br /> \r\n");
      out.write("                   <input type=\"checkbox\" name=\"saveId\" id=\"saveId\"  ");
      out.print(saveIdflag?"checked":"" );
      out.write(" />\r\n");
      out.write("                   <label for=\"saveId\">아이디 저장</label> \r\n");
      out.write("                  <br />\r\n");
      out.write("                  <button type=\"button\" id=\"loginBtn\" class=\"btn btn-secondary\" onclick=\"checkLogin();\" >Login</button>\r\n");
      out.write("               \r\n");
      out.write("               <br />\r\n");
      out.write("            </form>\r\n");
      out.write("            <ul id=\"link\">\r\n");
      out.write("               <li>\r\n");
      out.write("               <a href=\"");
      out.print(request.getContextPath());
      out.write("/views/user/userJoin\">회원가입</a></li>\r\n");
      out.write("               <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/user/findId_pwd\">아이디/비밀번호 찾기</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("         ");

            } else if(userLoggedIn.getUserId().equals("admin")){
      out.write("\r\n");
      out.write("            <div id=\"login-container\">\r\n");
      out.write("\r\n");
      out.write("            <span id=\"hi\">관리자님 안녕하세요!</span><img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/user.svg\" alt=\"\"\r\n");
      out.write("               id=\"user_profile_photo\" />\r\n");
      out.write("            <ul id=\"link\">\r\n");
      out.write("               <li><span><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/message/myMessage?userId=");
      out.print(userLoggedIn.getUserId());
      out.write("\">내쪽지함</a></span></li>\r\n");
      out.write("               <li><span><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/adminInfo\">관리자 페이지</a></span></li>\r\n");
      out.write("               <li><span><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/user/userLogout\">로그아웃</a></span></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </div>   \r\n");
      out.write("         \r\n");
      out.write("         ");
}else{
      out.write("\r\n");
      out.write("         <div id=\"login-container\">\r\n");
      out.write("            <div id=\"contnet\">\r\n");
      out.write("            <span id=\"hi\">");
      out.print(userLoggedIn.getName() );
      out.write("님 안녕하세요!</span> <img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/user.svg\" alt=\"\"\r\n");
      out.write("               id=\"user_profile_photo\" />\r\n");
      out.write("            <ul id=\"link\">\r\n");
      out.write("               <li><span><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/message/myMessage?userId=");
      out.print(userLoggedIn.getUserId());
      out.write("\">내쪽지함</a></span>\r\n");
      out.write("                  &nbsp; &nbsp;<span><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/user/userInfo?userId=");
      out.print(userLoggedIn.getUserId());
      out.write("\">내정보</a></span></li>\r\n");
      out.write("               <li><span id=\"userPoint\">포인트 :  ");
      out.print(userLoggedIn.getPoint() );
      out.write("P</span></li>\r\n");
      out.write("               <li>\r\n");
      out.write("               <span id=\"pullPoint\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/point/pointCharge?userId=");
      out.print(userLoggedIn.getUserId());
      out.write("\" >충전하기</a></span>&nbsp;&nbsp;\r\n");
      out.write("               <span id=\"changePoint\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/point/pointCharge?userId=");
      out.print(userLoggedIn.getUserId());
      out.write("\" >환전하기</a></span>\r\n");
      out.write("               </li>\r\n");
      out.write("               <li><span><a href=\"");
      out.print(request.getContextPath());
      out.write("/views/user/userLogout\">로그아웃</a></span></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         ");
}
      out.write("\r\n");
      out.write("         <div id=\"board-list-container\">\r\n");
      out.write("            <p id=\"board_title\">판매/구매</p>\r\n");
      out.write("            <ul class=\"boardList\">\r\n");
      out.write("               <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/sell/sellList\">판매 게시판</a></li>\r\n");
      out.write("               <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/buy/buyList\">구매 게시판</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <p id=\"board_title\">자유게시판</p>\r\n");
      out.write("            <ul class=\"boardList\">\r\n");
      out.write("               <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/free/freeList\">잡담 게시판</a></li>\r\n");
      out.write("               <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/free/senseList\">유용한 생활지식</a></li>\r\n");
      out.write("               <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/free/entertainList\">연예/미디어</a></li> \r\n");
      out.write("               <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/free/divideList\">나눔 게시판</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <p id=\"board_title\">건의사항/신고</p>\r\n");
      out.write("            <ul class=\"boardList\">\r\n");
      out.write("               <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/opinion/opinionList\">건의 게시판</a></li>\r\n");
      out.write("               <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/opinion/declarationList\">신고 게시판</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <p id=\"board_title\">기타</p>\r\n");
      out.write("            <ul class=\"boardList\">\r\n");
      out.write("               <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/others/partnerList\">협력사 모아보기</a></li>\r\n");
      out.write("               <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/others/faqList\">QnA </a><br><br></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("      </section>\r\n");
      out.write("   </aside>\r\n");
      out.write("\r\n");
      out.write("   <aside id=\"asideRight\">\r\n");
      out.write("      <section>\r\n");
      out.write("         <div id=\"weather-day\">\r\n");
      out.write("         </div>\r\n");
      out.write("         <div id=\"ad1\" class=\"ad\">\r\n");
      out.write("            <a href=\"https://audioclip.naver.com/channels/2212\"> <img src=\"https://ssl.pstatic.net/tveta/libs/1222/1222741/4700e66469135fe571c9_20190522110854287.jpg\" alt=\"\" /> \r\n");
      out.write("            </a>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div id=\"ad2\" class=\"ad\">\r\n");
      out.write("            <a href=\"http://mhorigin.noblegames.kr/simplejoin/\"> <img\r\n");
      out.write("               src=\"https://ssl.pstatic.net/tveta/libs/1242/1242071/2c71934b68f1550955f4_20190607145802832.jpg\" alt=\"\" />\r\n");
      out.write("            </a>\r\n");
      out.write("         </div>\r\n");
      out.write("      </section>\r\n");
      out.write("   </aside>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("\t<script>\r\n");
      out.write("\t\t//날씨정보 api불러오기\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\tvar location = \"Seoul\";\r\n");
      out.write("\t\t\tvar today = new Date();\r\n");
      out.write("\t\t\tvar dd = today.getDate();\r\n");
      out.write("\t\t\tvar mm = today.getMonth() + 1; //January is 0!\r\n");
      out.write("\t\t\tvar yyyy = today.getFullYear();\r\n");
      out.write("\t\t\tif (dd < 10) {\r\n");
      out.write("\t\t\t\tdd = '0' + dd\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (mm < 10) {\r\n");
      out.write("\t\t\t\tmm = '0' + mm\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\ttoday = yyyy + \"년\" + mm + \"월\" + dd + \"일\";\r\n");
      out.write("\t\t\tvar apiUrl = \"http://api.openweathermap.org/data/2.5/weather?q=Seoul&appid=d69250224a399641ef739b6e02e5cfaf\";\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl : apiUrl,\r\n");
      out.write("\t\t\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\t\t\ttype : \"GET\",\r\n");
      out.write("\t\t\t\t\t\tasync : \"false\",\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(resp) {\r\n");
      out.write("\t\t\t\t\t\t\tvar imgURL = \"http://openweathermap.org/img/w/\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ resp.weather[0].icon + \".png\";\r\n");
      out.write("\t\t\t\t\t\t\tvar html = '<div id=\"weather\"><span style=\"font-size:20px;\" id=\"today\">'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ today\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ '</span><img src=\"'+imgURL+'\" alt=\"\" />';\r\n");
      out.write("\t\t\t\t\t\t\t\t/* 날씨 설명이 너무 길어질 때가 있어 생략함.\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(!resp.weather[0].description.length>5){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thtml+='<span id=\"wSpan\"><nobr>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ resp.weather[0].description\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ '</nobr></span><br />';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thtml+='<span id=\"wSpan2\"><nobr>'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ resp.weather[0].description\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ '</nobr></span><br />';\r\n");
      out.write("\t\t\t\t\t\t\t\t\t} */\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\thtml+='<br /><span>현재위치 : '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ resp.name\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ '</span><br />';\r\n");
      out.write("\t\t\t\t\t\t\thtml += '<span>현재온도 : '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ Math\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t.round((resp.main.temp - 273.15) * 10.0)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t/ 10.0 + '°C</span><br /><span>현재습도 : '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ resp.main.humidity + '%</span><br />';\r\n");
      out.write("\t\t\t\t\t\t\thtml += '<span>풍속 : ' + resp.wind.speed\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ ' m/s</span></div><br />';\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#weather-day\").append(html);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//로그인 처리\r\n");
      out.write("\t\tfunction checkLogin() {\r\n");
      out.write("\t\t\tvar id = $('#header_userId').val().trim();\r\n");
      out.write("\t\t\tvar pwd = $('#header_userPwd').val().trim();\r\n");
      out.write("\t\t\tif (id.length == 0) {\r\n");
      out.write("\t\t\t\talert('아이디를 입력해주세요.');\r\n");
      out.write("\t\t\t\t$('#header_userId').focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tif (pwd.length == 0) {\r\n");
      out.write("\t\t\t\t\talert('비밀번호를 입력해주세요.');\r\n");
      out.write("\t\t\t\t\t$('#header_userPwd').focus();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#loginFrm').submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction enterUser(){\r\n");
      out.write("\t\t\tif(window.event.keyCode==13){\r\n");
      out.write("\t\t\t\tcheckLogin();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\n");
      out.write("\t</script>\r\n");
      out.write("\t<section id=\"content\">\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

Sell b = (Sell)request.getAttribute("sell");

Sell prev = (Sell)request.getAttribute("prev");
Sell next = (Sell)request.getAttribute("next");
List<Comment> commentList = (List<Comment>)request.getAttribute("cList");
List<FileTable> file = (List<FileTable>)request.getAttribute("files");

      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Gothic+A1|Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrap cdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/header.css\" /> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/board/boardView.css\" /> \r\n");
      out.write("\r\n");
      out.write("<article id=\"article\">\r\n");
      out.write("\r\n");
      out.write("\t<h2 style=\"text-align: center;\">판매 게시판</h2>\r\n");
      out.write("\t<div id=\"div1\" style=\"text-align: center;\">\r\n");
      out.write("\r\n");
      out.write("\t\t<span id=\"boardTitle\" name=\"boardTilte\">");
      out.print(b.getBoardTitle() );
      out.write("</span>\r\n");
      out.write("\t\t<span id=\"k_span\">");
      out.print(b.getBoardCodeNo() );
      out.write("</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"ed_box\">\r\n");
      out.write("\t\t<span class=\"id\">");
      out.print(b.getBoardWriter());
      out.write("</span> <span\r\n");
      out.write("\t\t\tclass=\"ed text-xsmall text-muted\">");
      out.print(b.getBoardDate() );
      out.write("</span> <span\r\n");
      out.write("\t\t\tclass=\"ed text-xsmall text-muted\">조회수 ");
      out.print(b.getBoardReadCounter() );
      out.write("</span>\r\n");
      out.write("\t\t<div id=\"div-message\">\r\n");
      out.write("\t\t\t");
if(userLoggedIn != null){ 
      out.write("\r\n");
      out.write("\t\t\t<a onclick=\"reply('");
      out.print(userLoggedIn.getUserId() );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(b.getBoardWriter() );
      out.write("');\"\r\n");
      out.write("\t\t\t\tid=\"message_href\">☏ 쪽지보내기</a> \r\n");
      out.write("\t\t\t<a onclick=\"interest_btn('");
      out.print(userLoggedIn.getUserId() );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(b.getBoardNo());
      out.write("');\"\r\n");
      out.write("\t\t\t\tid=\"interest_btn\">☆ 관심등록</a> \r\n");
      out.write("\t\t\t\t<input type=\"hidden\" value=\"0\" id=\"interest_val\">\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t <div id=\"boardContent\" style=\"width: 590px; height:400px; border: 0.2px solid lightgrayv; margin: auto;\">\r\n");
      out.write("            <div style=\"width: 100%; border: 1px solid; margin-top: 28px; margin-left: -16px;\" >파일내려받기 or 거래방식 넣을곳임</div>\r\n");
      out.write("               ");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <div style=\"width: 100%; margin-left: -16px; min-height: 360px; margin-top: 10px;\">\r\n");
      out.write("                ");
      out.print(b.getBoardContent() );
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"min_div\" style=\"margin-left: 15%;\">\r\n");
      out.write("\t\t<table id=\"min_index\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><a onclick=\"next_btn();\" id=\"next_btn\"> [다음글 : ");
      out.print(next!=null?next.getBoardTitle():"다음글 없습니다");
      out.write(" ]</a></td>  \r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td><a onclick=\"prev_btn();\" id=\"prev_btn\"> [이전글 : ");
      out.print(prev!=null?prev.getBoardTitle():"이전글 없습니다");
      out.write(" ]</a></td>  \r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"buttons\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t");
 if(userLoggedIn != null){
			if( b.getBoardWriter().equals(userLoggedIn.getUserId())
        			|| "admin".equals(userLoggedIn.getUserId())){ 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"수정\"\r\n");
      out.write("\t\t\t\tonclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/sell/sellModified?boardNo=");
      out.print(b.getBoardNo());
      out.write("'\" />\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"삭제\" onclick=\"deleteBoard();\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
} }
      out.write("\r\n");
      out.write("\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\tonclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/sell/sellList'\">목록</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<Br>\r\n");
      out.write("\t\t<div id=\"comment-container\" style=\"text-align: center;\">\r\n");
      out.write("\t\t\t<div class=\"comment-editor\">\r\n");
      out.write("\t\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/sell/sellComment\"\r\n");
      out.write("\t\t\t\t\tname=\"boardCommentFrm\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<textarea name=\"commentContent\" cols=\"70\" rows=\"2\" maxlength=\"65\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"65자까지만 작성 할 수 있습니다.\"></textarea>\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" id=\"btn-insert\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"position: relative; top: -9px;\">등록</button>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"boardNo\" value=\"");
      out.print(b.getBoardNo() );
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"commentWriter\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(userLoggedIn!=null?userLoggedIn.getUserId():"");
      out.write("\" /> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"hidden\" name=\"commentLevel\" value=\"1\" /> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"hidden\" name=\"commentNoRef\" value=\"0\" />\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 댓글목록 테이블 -->\r\n");
      out.write("\t\t\t<div id=\"div-comment\">\r\n");
      out.write("\t\t\t\t<table id=\"tbl-comment\">\r\n");
      out.write("\t\t\t\t\t");
if(!commentList.isEmpty()) {
		for(Comment bc: commentList){
			if(bc.getCommentLevel()==1){
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 댓글인경우 -->\r\n");
      out.write("\t\t\t\t\t<tr class=\"level1\">\r\n");
      out.write("\t\t\t\t\t\t<td id=\"CommentContents\"><sub class=\"comment-writer\">");
      out.print(bc.getCommentWriter() );
      out.write("</sub>\r\n");
      out.write("\t\t\t\t\t\t\t<sub class=\"comment-date\">");
      out.print(bc.getCommentDate() );
      out.write("</sub> <br />\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(bc.getCommentContent() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"text-align: left; width: 120px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn-reply\" value=\"");
      out.print(bc.getCommentNo() );
      out.write("\">답글</button>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t");
if(userLoggedIn!=null 
						&& ("admin".equals(userLoggedIn.getUserId()) 
								|| bc.getCommentWriter().equals(userLoggedIn.getUserId()) )){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn-delete\" value=\"");
      out.print(bc.getCommentNo());
      out.write("\">삭제</button>\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");
			
			}else{
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 대댓글인경우 -->\r\n");
      out.write("\t\t\t\t\t<tr class=\"level2\">\r\n");
      out.write("\t\t\t\t\t\t<td id=\"CommentContentsReply\">\r\n");
      out.write("\t\t\t\t\t\t<sub class=\"comment-writer\">↳");
      out.print(bc.getCommentWriter());
      out.write("</sub>\r\n");
      out.write("\t\t\t\t\t\t\t<sub class=\"comment-date\">");
      out.print(bc.getCommentDate() );
      out.write("</sub> <br />\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(bc.getCommentContent() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"text-align: left; width: 120px;\"> \r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write(' ');
if(userLoggedIn!=null && ("admin".equals(userLoggedIn.getUserId()) 
							|| bc.getCommentWriter().equals(userLoggedIn.getUserId()) )){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn-delete\" value=\"");
      out.print(bc.getCommentNo());
      out.write("\" >삭제</button>\r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
			
			}//end of if(bc.getBoardCommentLevel()==1)
		
		}//end of for
		
	}//end of if(!commentList.isEmpty())
	
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function prev_btn() {\r\n");
      out.write("\t\r\n");
      out.write("\tif('");
      out.print(prev.getBoardTitle());
      out.write("'=='null'){\r\n");
      out.write("\t\talert('이전글이 없습니다');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\tvar boardNo = '");
      out.print(b.getBoardNo());
      out.write("';\r\n");
      out.write("    var b1 = boardNo.substr(0,2);\r\n");
      out.write("    var b2 = Number(boardNo.substr(2))-1;\r\n");
      out.write("\tboardNo = b1+b2\r\n");
      out.write("\tconsole.log(boardNo)\r\n");
      out.write("\t\r\n");
      out.write(" location.href=\"");
      out.print(request.getContextPath());
      out.write("/sell/sellView?boardNo=");
      out.print(prev.getBoardNo());
      out.write("\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function next_btn() {\r\n");
      out.write("\t\r\n");
      out.write("\tif('");
      out.print(next.getBoardTitle());
      out.write("'=='null'){\r\n");
      out.write("\t\talert('다음글이 없습니다');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\tvar boardNo = '");
      out.print(b.getBoardNo());
      out.write("';\r\n");
      out.write("\t var b1 = boardNo.substr(0,2);\r\n");
      out.write("\t    var b2 =Number(boardNo.substr(2))+1;\r\n");
      out.write("\t\tboardNo = b1+b2\r\n");
      out.write("\t\tconsole.log(boardNo)\r\n");
      out.write("\t\t\r\n");
      out.write("\t location.href=\"");
      out.print(request.getContextPath());
      out.write("/sell/sellView?boardNo=");
      out.print(next.getBoardNo());
      out.write("\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("(function on_interest(userId,boardNo) {\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/board/boardinterestcheck\",\r\n");
      out.write("\t\tdata: {userId : '");
      out.print(userLoggedIn!=null?userLoggedIn.getUserId():"");
      out.write("', boardNo : '");
      out.print(b.getBoardNo());
      out.write("'},\r\n");
      out.write("\t\tsuccess: function(data){\r\n");
      out.write("\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//넘어온 csv데이터가, 공백인경우\r\n");
      out.write("\t\t\tif(data.trim().length == '0'){\r\n");
      out.write("\t\t\t\tconsole.log(\"관심글 x\");\r\n");
      out.write("\t\t\t\t$(\"#interest_val\").val(0);\r\n");
      out.write("\t\t\t\t$(\"#interest_btn\").text('☆관심등록');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\tconsole.log(\"관심글 o\");\r\n");
      out.write("\t\t\t\t$(\"#interest_val\").val(1);\r\n");
      out.write("\t\t\t\t$(\"#interest_btn\").text('★관심등록');\r\n");
      out.write("\t\t\t\t}\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("})();\r\n");
      out.write("\r\n");
      out.write("//관심글 등록 함수\r\n");
      out.write("function interest_btn(userId,boardNo) {\r\n");
      out.write("\t\r\n");
      out.write(" if('");
      out.print(b.getBoardWriter());
      out.write("'==userId){\r\n");
      out.write("\t\talert('본인글 입니다');\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\tif($(\"#interest_val\").val()==0){\r\n");
      out.write("\t\tconsole.log(\"추가 실행\")\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\t\r\n");
      out.write("\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/board/boardinterest\",\r\n");
      out.write("\t\tdata: {userId : userId, boardNo : boardNo},\r\n");
      out.write("\t\tsuccess: function(data){\r\n");
      out.write("\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//넘어온 csv데이터가, 공백인경우\r\n");
      out.write("\t\t\tif(data.trim().length == 0){\r\n");
      out.write("\t\t\t\tconsole.log(\"공백넘어옴\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\t\talert(\"관심글 등록완료\");\r\n");
      out.write("\t\t\t\t\t$(\"#interest_val\").val(1);\r\n");
      out.write("\t\t\t\t\t$(\"#interest_btn\").text('★관심등록');\r\n");
      out.write("\t\t\t\t}\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t} //end if\r\n");
      out.write("\telse {\r\n");
      out.write("\t\tconsole.log(\"삭제 실행\");\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/board/boardinterestdelete\",\r\n");
      out.write("\t\t\tdata: {userId : userId, boardNo : boardNo},\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//넘어온 csv데이터가, 공백인경우\r\n");
      out.write("\t\t\t\tif(data.trim().length == 0){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"공백넘어옴\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\talert(\"관심글 제거완료\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#interest_val\").val(0);\r\n");
      out.write("\t\t\t\t\t\t$(\"#interest_btn\").text('☆관심등록');\r\n");
      out.write("\t\t\t\t\t}\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t}//end else\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function reply(sender,recipient){\r\n");
      out.write("\t//사용자가 sender, 받는사람이 recipient\r\n");
      out.write("\tvar url=\"");
      out.print(request.getContextPath());
      out.write("/views/message/messageReply?senderId=\"+sender+\"&recipient=\"+recipient;\r\n");
      out.write("\tvar title=\"쪽지 보내기\";\r\n");
      out.write("\tvar specs=\"width=460px, height=500px, left=500px, top=200px\";\r\n");
      out.write("\tvar popup=open(url, title,specs);\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function loginAlert(){\r\n");
      out.write("\talert('로그인이 필요한 기능입니다.');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function deleteBoard(){\r\n");
      out.write("\tif(!confirm(\"정말 삭제하시겠습니까?\")) return;\r\n");
      out.write("\t//삭제처리후 돌아올 현재게시판번호도 함께 전송함.\r\n");
      out.write("\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/sell/sellDelete?boardNo=");
      out.print(b.getBoardNo());
      out.write("\";\r\n");
      out.write("}\r\n");
      out.write("function deleteComment(obj){\r\n");
      out.write("\tconsole.log(obj.value);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(function() {\r\n");
      out.write("\t //대댓글입력\r\n");
      out.write("   $(\".btn-reply\").click(function(){\r\n");
      out.write("       /* 로그인여부확인 */\r\n");
      out.write("       ");
 if(userLoggedIn == null){ 
      out.write("\r\n");
      out.write("           loginAlert();\r\n");
      out.write("       ");
 } else {
      out.write("\r\n");
      out.write("           var tr = $(\"<tr></tr>\");\r\n");
      out.write("           var html = '<td style=\"display:none; text-align:left;\" colspan=\"2\">';\r\n");
      out.write("           html += '<form action=\"");
      out.print(request.getContextPath());
      out.write("/sell/sellComment\" method=\"post\">';\r\n");
      out.write("           html += '<textarea name=\"commentContent\" cols=\"60\" rows=\"3\"></textarea>';\r\n");
      out.write("           html += '<input type=\"hidden\" name=\"boardNo\" value=\"");
      out.print(b.getBoardNo() );
      out.write("\" />';\r\n");
      out.write("           html += '<input type=\"hidden\" name=\"commentWriter\" value=\"");
      out.print(userLoggedIn!=null?userLoggedIn.getUserId():"");
      out.write("\" />';\r\n");
      out.write("           html += '<input type=\"hidden\" name=\"commentLevel\" value=\"2\" />';\r\n");
      out.write("           html += '<input type=\"hidden\" name=\"commentNoRef\" value=\"'+$(this).val()+'\" />';\r\n");
      out.write("           html += '<br><button style=\"margin-left: 396px;\" type=\"submit\" class=\"btn-insert2\">등록</button>';      \r\n");
      out.write("           html += '</form></td>';\r\n");
      out.write("     \r\n");
      out.write("           tr.html(html);\r\n");
      out.write("           tr.insertAfter($(this).parent().parent()).children(\"td\").slideDown(800);\r\n");
      out.write("       \r\n");
      out.write("           //답글버튼을 연속적으로 누르지 않도록 핸들러제거\r\n");
      out.write("           $(this).off('click');\r\n");
      out.write("           \r\n");
      out.write("           //새로생성한 요소에 대해 submit이벤트 핸들러 작성\r\n");
      out.write("           tr.find(\"form\").submit(function(e){\r\n");
      out.write("               //댓글 textarea 유효성검사\r\n");
      out.write("               var content = $(this).children(\"textarea\").val().trim();\r\n");
      out.write("               if(content.length == 0){\r\n");
      out.write("                   e.preventDefault();\r\n");
      out.write("               }\r\n");
      out.write("           });\r\n");
      out.write("       ");
 } 
      out.write("\r\n");
      out.write("   });\r\n");
      out.write("\t \r\n");
      out.write("\r\n");
      out.write("   $('.btn-delete').click(function(){\r\n");
      out.write("\t\t var bool=confirm('댓글을 삭제하시겠습니까??');\r\n");
      out.write("\t\t if(bool){\r\n");
      out.write("\t\t\t location.href=\"");
      out.print(request.getContextPath());
      out.write("/sell/sellCommentDelete?commentNo=\"+$(this).val()+\"&boardNo=");
      out.print(b.getBoardNo());
      out.write("\";\r\n");
      out.write("\t\t }else{\r\n");
      out.write("\t\t\t return;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t \r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</article>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/footer.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#footer{\r\n");
      out.write("background-image: url('");
      out.print(request.getContextPath());
      out.write("/images/footer.jpg');\r\n");
      out.write("\r\n");
      out.write("} \r\n");
      out.write("</style>\r\n");
      out.write("</section>\r\n");
      out.write("<footer>\r\n");
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
